{
	"version": 1747530390,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/menu2-sheet0.png",
		"images/menu2-sheet1.png",
		"images/menu2-sheet2.png",
		"images/menu2-sheet3.png",
		"images/menu2-sheet4.png",
		"images/menu2-sheet5.png",
		"images/titulo-sheet0.png",
		"images/tiledbackground.png",
		"images/laser2-sheet0.png",
		"images/muro-sheet0.png",
		"images/muro3-sheet0.png",
		"images/laser-sheet0.png",
		"images/fuego-sheet0.png",
		"images/fuego-sheet1.png",
		"images/muro2-sheet0.png",
		"images/bala-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/item-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/electric-sheet0.png",
		"images/robot-sheet0.png",
		"images/laser3-sheet0.png",
		"images/star-sheet0.png",
		"images/cañon2-sheet0.png",
		"images/cañon-sheet0.png",
		"media/x2download.app - 8 bit coin sound effect (128 kbps).ogg",
		"media/x2download.app - 8- bit explosion sound effect [sfx] (128 kbps).ogg",
		"media/x2download.app - laser sound effect (128 kbps).ogg",
		"media/x2download.app-8 bit victory non copyright sound effect _ ncsfx-(128kbps).ogg",
		"media/x2download.app-efecto de sonido de disparo retro _para shooters de 8bits_ _ effectblox (mp3cut.net).ogg",
		"media/x2download.app-laser _ sound effect 8-bits-(128kbps).ogg",
		"media/intromusic.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}